import { ArrowRight, BadgeCheck, CheckCircle2, FileImage, FileText, Link2, MessageSquareText, QrCode, Shield, ShieldCheck, Sparkles, UploadCloud, Volume2, XCircle } from 'lucide-react'
import { Link } from 'react-router-dom'

const inspectModes = [
  { icon: MessageSquareText, title: 'SMS & WhatsApp Forward', copy: 'Electricity, bank, KYC or payment alerts.', cta: 'Check message', to: '/check' },
  { icon: FileImage, title: 'Screenshots & Notices', copy: 'Fake invoices, QR images and urgent notices.', cta: 'Upload image', to: '/check' },
  { icon: Link2, title: 'Websites & Links', copy: 'Suspicious domains, redirects and short links.', cta: 'Scan domain', to: '/check' },
  { icon: Volume2, title: 'Call Audio & Voice', copy: 'Caller-pressure patterns and OTP requests.', cta: 'Analyze audio', to: '/check' },
  { icon: QrCode, title: 'UPI QR Codes', copy: 'Check a QR payload without opening it.', cta: 'Verify QR', to: '/check' },
]

const trustCards = [
  ['Understand intent', 'A plain-language read of what the sender is trying to make you do.', MessageSquareText],
  ['Psychological & technical triage', 'Urgency, impersonation, payment pressure and link behavior in one view.', Sparkles],
  ['Actionable safe directions', 'Clear “do” and “don’t” guidance for you and your family.', ShieldCheck],
]

const safetyCards = [
  ['No personal logins', 'No accounts, passwords or unnecessary personal details required.', XCircle],
  ['Vaulted server analysis', 'Uploads are processed temporarily and raw content is not stored by default.', ShieldCheck],
  ['Localization first', 'Parent Mode keeps explanations simple across Indian languages.', Volume2],
  ['Non-punitive family care', 'Designed to make it easier to ask for help before acting.', BadgeCheck],
]

export function HomePage() {
  return <>
    <main>
      <section className="bg-paper"><div className="container-shell grid items-center gap-12 py-14 lg:grid-cols-[1fr_.92fr] lg:py-20">
        <div><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-brand-soft px-3 py-1.5 font-label text-xs font-semibold text-brand"><ShieldCheck size={15} /> AI for safer decisions in Indian digital life</div><h1 className="max-w-2xl text-4xl font-bold leading-tight sm:text-5xl">Before you click, pay, or share — <span className="text-brand">check it.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-muted sm:text-lg">ScamShield Bharat uses AI to analyze suspicious messages, screenshots, links and voice notes, then tells you exactly what to do next.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/check" className="btn-primary"><ShieldCheck size={17} />Check something suspicious</Link><a href="#how-it-works" className="btn-secondary">See how it works</a></div><div className="mt-6 grid max-w-xl grid-cols-2 gap-2 sm:grid-cols-4"><span className="rounded-xl bg-white p-3 text-xs text-muted shadow-card"><strong className="block text-ink">No account</strong> required</span><span className="rounded-xl bg-white p-3 text-xs text-muted shadow-card"><strong className="block text-ink">Zero credential</strong> storage</span><span className="rounded-xl bg-white p-3 text-xs text-muted shadow-card"><strong className="block text-ink">14 languages</strong> planned</span><span className="rounded-xl bg-white p-3 text-xs text-muted shadow-card"><strong className="block text-ink">Free public</strong> utility</span></div></div>
        <div className="relative"><div className="absolute -inset-5 rounded-[2rem] bg-brand/10 blur-3xl"/><div className="relative rounded-3xl border border-line bg-white p-4 shadow-soft"><div className="flex items-center justify-between border-b border-line px-2 pb-4"><div className="flex items-center gap-2"><Shield size={17} className="text-brand" /><span className="font-label text-xs font-bold uppercase tracking-[.12em] text-muted">Live analysis stream</span></div><span className="rounded-full bg-success-soft px-2.5 py-1 font-label text-[10px] font-bold text-success-dark">Sample inspection</span></div><div className="mt-5 rounded-2xl bg-paper p-5"><div className="flex items-center justify-between gap-4"><p className="font-label text-[10px] font-bold uppercase tracking-[.12em] text-muted">WhatsApp forward</p><span className="font-label text-[10px] text-muted">Just now</span></div><p className="mt-4 text-sm font-semibold leading-6 text-ink">“Your KYC has expired. Click here immediately to prevent account suspension.”</p><p className="mt-3 text-xs text-muted">Sent from an unverified contact</p></div><div className="mt-4 rounded-2xl border border-red-100 bg-danger-soft p-4 shadow-critical"><div className="flex items-center justify-between"><span className="font-label rounded-full bg-danger px-3 py-1 text-[10px] font-bold tracking-[.1em] text-white">HIGH RISK</span><span className="font-label text-[10px] font-bold text-danger-dark">04 signals found</span></div><p className="mt-3 font-semibold text-danger-dark">Potential phishing / impersonation attempt</p><p className="mt-1 text-xs leading-5 text-red-900/70">Urgency, impersonation and external action detected.</p></div><div className="mt-4 rounded-2xl border border-emerald-100 bg-success-soft p-4 shadow-safe"><p className="font-label text-[10px] font-bold uppercase tracking-[.12em] text-success-dark">Safer next step</p><p className="mt-2 text-sm font-semibold text-emerald-950">Open the official app manually. Don’t click the link.</p></div></div></div>
      </div></section>

      <section className="border-y border-line bg-white"><div className="container-shell grid gap-6 py-8 sm:grid-cols-3"><div><p className="text-2xl font-bold text-ink">1.8M+</p><p className="mt-1 text-xs text-muted">Indian cybercrime complaints reported annually</p></div><div><p className="text-2xl font-bold text-ink">&lt;1.2s</p><p className="mt-1 text-xs text-muted">Average time to understand a suspicious message</p></div><div><p className="text-2xl font-bold text-success-dark">Zero stored</p><p className="mt-1 text-xs text-muted">Passwords, bank credentials or raw uploads</p></div></div></section>

      <section id="how-it-works" className="container-shell py-16 sm:py-20"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">The protective layer</span><h2 className="mt-3 text-3xl font-semibold sm:text-4xl">Designed for everyday families, not cybersecurity analysts.</h2><p className="mt-4 text-sm leading-6 text-muted">Three simple stages turn confusing digital pressure into a calm, safer choice.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{trustCards.map(([title, copy, Icon]) => <article key={title as string} className="card p-6"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-brand-soft text-brand"><Icon size={19} /></div><h3 className="mt-7 text-lg font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted">{copy as string}</p><div className="mt-5 flex items-center gap-2 font-label text-[10px] font-semibold uppercase tracking-[.1em] text-success-dark"><CheckCircle2 size={14} /> Built for clarity</div></article>)}</div></section>

      <section className="bg-[#eff4ff]"><div className="container-shell py-16 sm:py-20"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="eyebrow">Input coverage</span><h2 className="mt-3 text-3xl font-semibold">What would you like to inspect right now?</h2><p className="mt-2 text-sm text-muted">Choose a communication medium. You can paste text, upload screenshots or send an audio recording.</p></div><Link to="/check" className="text-sm font-bold text-brand">Open the scanner <ArrowRight className="ml-1 inline" size={15} /></Link></div><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{inspectModes.map(({ icon: Icon, title, copy, cta, to }) => <article key={title} className="rounded-2xl border border-white bg-white p-4 shadow-card"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-brand-soft text-brand"><Icon size={17} /></div><h3 className="mt-6 text-sm font-semibold">{title}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-muted">{copy}</p><Link to={to} className="mt-5 inline-flex items-center gap-1 font-label text-[10px] font-bold text-brand">{cta} <ArrowRight size={13} /></Link></article>)}</div></div></section>

      <section className="container-shell py-16 sm:py-20"><div className="flex items-end justify-between gap-4"><div><span className="eyebrow">Curated threats in India</span><h2 className="mt-3 text-3xl font-semibold">Deconstructed scam playbooks</h2></div><Link to="/learn" className="hidden text-sm font-bold text-brand sm:block">Browse the scam library <ArrowRight className="ml-1 inline" size={15} /></Link></div><div className="mt-8 grid gap-4 md:grid-cols-2"><div className="card p-5"><div className="flex items-center justify-between"><span className="font-label rounded-full bg-danger-soft px-2.5 py-1 text-[10px] font-bold text-danger-dark">Reported in India</span><span className="font-label text-[10px] text-muted">Banking / UPI</span></div><h3 className="mt-5 font-semibold">Electricity suspension impersonation</h3><p className="mt-2 text-sm leading-6 text-muted">A fake utility notice threatens a power cut, then asks the family to install an app or share an OTP.</p><div className="mt-5 flex items-center gap-2 rounded-xl bg-paper p-3 text-xs text-muted"><BadgeCheck className="text-success-dark" size={15} /> ScamShield explains the pressure pattern, not just the keywords.</div></div><div className="card p-5"><div className="flex items-center justify-between"><span className="font-label rounded-full bg-amber-soft px-2.5 py-1 text-[10px] font-bold text-amber-dark">High frequency</span><span className="font-label text-[10px] text-muted">Delivery / refund</span></div><h3 className="mt-5 font-semibold">The tiny refund trap</h3><p className="mt-2 text-sm leading-6 text-muted">A missed-delivery message uses a small fee or refund form to redirect a user into a payment flow.</p><div className="mt-5 flex items-center gap-2 rounded-xl bg-paper p-3 text-xs text-muted"><BadgeCheck className="text-success-dark" size={15} /> The safest move is to open the official app yourself.</div></div></div></section>

      <section className="bg-[#eff4ff]"><div className="container-shell py-16 sm:py-20"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">A protective utility</span><h2 className="mt-3 text-3xl font-semibold">Zero-trust privacy engineered for civic reassurance.</h2><p className="mt-4 text-sm leading-6 text-muted">We protect your parents and family members without snooping, logging credentials or collecting extra information.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{safetyCards.map(([title, copy, Icon]) => <article className="rounded-2xl border border-white bg-white p-5 shadow-card" key={title as string}><Icon className="text-brand" size={19} /><h3 className="mt-5 text-sm font-semibold">{title as string}</h3><p className="mt-2 text-xs leading-5 text-muted">{copy as string}</p></article>)}</div></div></section>

      <section className="container-shell py-16"><div className="flex flex-col items-center justify-between gap-5 rounded-3xl border border-line bg-white p-6 shadow-card sm:flex-row"><div className="flex items-start gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-danger-soft text-danger-dark"><UploadCloud size={18} /></div><div><span className="font-label rounded-full bg-danger px-2 py-1 text-[9px] font-bold uppercase text-white">Cyber-fraud support</span><h3 className="mt-2 text-lg font-semibold">Already sent money or shared a banking OTP?</h3><p className="mt-1 text-sm leading-6 text-muted">Contact your bank immediately and call 1930. Preserve your screenshots and transaction references.</p></div></div><Link to="/emergency" className="btn-primary shrink-0 bg-danger-dark hover:bg-red-700">I may have been scammed <ArrowRight size={16} /></Link></div></section>
    </main>
  </>
}
